repos:
  - repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
    - id: black
      language_version: python3

  - repo: https://github.com/bufbuild/buf
    # Also update version in .github/workflows/protobuf.yaml
    rev: v1.39.0
    hooks:
      - id: buf-lint
        args: [src/protobuf]
        fail_fast: true
      - id: buf-format
        args: [src/protobuf]

